sudo: required
dist: xenial
language: scala

before_install:
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.1/install.sh | bash && . ~/.jabba/jabba.sh
  - jabba install adopt@~1.8.0-202


before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.jabba/jdk

script:
  - jabba use ${JDK:=adopt@~1.8.0-202}
  - ./scripts/setup-minikube-for-linux.sh && sbt "it:test"
