version: ~> 1.0
dist: xenial
addons:
  apt:
    packages:
    - conntrack
language: scala

before_install:
  - curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
  - jabba install adopt@~1.8.0-202


before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.jabba/jdk

script:
  - jabba use ${JDK:=adopt@~1.8.0-202}
  - ./scripts/setup-minikube-for-linux.sh && ./scripts/runTest.sh

notifications:
  email:
    recipients:
        ## Secret created using:
        ##  $ travis encrypt --pro "something@something.com"
        ##  Detected repository as ignasi35/akka-upgrade-testing, is this correct? |yes| no
        ##  Repository slug (owner/name): |ignasi35/akka-upgrade-testing| akka/akka-upgrade-testing
      secure: "nDnrjYGLpd6tJ+KZb7V8O+O4RE5waonjVZOPpuAl40VrHSuVOauNmb0ut7TcTkqAk1G0YmoxvumYu85vCy67kH9sgL0BXTsAu2zJJUNm3I9e92b8FuXpnWbTFC45SyYwOeFfdLOfDDbAk5rVWMQGKsCDTsqhuKZR+XAR4wwSgVgAFdhN/uQVyPXgwBGkAIbuMHuyvhb35y5JqpOvFYWO59Pd3DqrDq+tRm5l/3HpO6dYMYv472iF7xIRDVRUcANgJSZphlx2LGgO/H4BhPuY7yeQDmCrl3XD3ZczjrGPyOTpjQzo03vKL5fVisqotWiJkemlUBFXXork8TjsES6pfAB10JtNFksyI4pi1jmIbVvazG0VO3ZwNbtyFclZWlugIsv4lbvxWbyMWa29soN2pP0uVSSW1H3oR/RYlh7oCNAYPF5nFplSKqINbvyIrhOhvmusVRb/YKu5ekrpAHF5U+9147GACzOJSMkSx5hPNgXdG1Sko4BRq7O4EkAg29GXXnEIpV7u3b0wPCoGWYc3kdVlch8hy38VNqUzF1ZqLjk2QDOQiMhZu0TffrS0b+qLIaPbvxXcKdYLJ+VpJ5ysxJrHaRyoJSgquKjP7aV1GCaIUm4YnilWWNxjmVmgd6wIrmBw5dteTGw3WLn9Kwkciz5Rix0GiyoqI0wwz6P19HY="
    on_success: never
    on_failure: always
