#!/usr/bin/env bash

# Copyright (C) Lightbend Inc. <https://www.lightbend.com>

# Lib for CI scripts
# copied and adapted from https://github.com/lagom/lagom/blob/1738a589816c6b12e4f9bcc05b7cba4d184da3b6/bin/scriptLib#L5

set -e
set -o pipefail

EXTRA_OPTS=("")

# Check if it is a scheduled build
#if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
## Search for snapshots is harcdoded to scala 2.13
## Queries differ because the artifact names changed during the 2.6 milestones phase.
AKKA_25_SNAPSHOT=$(curl -s https://repo.akka.io/snapshots/com/typesafe/akka/akka-actor_2.13/ | grep -oEi '2\.5-[0-9]{8}-[0-9]{6}' | sort | tail -n 1)
AKKA_26_SNAPSHOT=$(curl -s https://repo.akka.io/snapshots/com/typesafe/akka/akka-actor_2.13/ | grep -oEi '2\.6\.[0-9]+\+[0-9]+-[0-9a-f]{8}' | sort -V | tail -n 1)

echo "Using Akka SNAPSHOTs [2.5: ${AKKA_26_SNAPSHOT}, 2.6: ${AKKA_26_SNAPSHOT}]"

EXTRA_OPTS+=("-Dcron.build.akka.25.snapshot=${AKKA_25_SNAPSHOT}")
EXTRA_OPTS+=("-Dcron.build.akka.26.snapshot=${AKKA_26_SNAPSHOT}")
#fi
